name: 'Update Json File'
description: 'This GitHub Action edits any key in a json file to the provided values'
author: 'Restack'
inputs:
  file:
    required: true
    description: "file name/path to edit. e.g 'package.json'"
  fields:
    required: true
    description: "fields to edit. can be nested fields. example: {'a.b.c[0]': 'value_here', 'z.x': 'value_here'}"
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'layers'
  color: 'purple'
